const state={csrf:"",tasks:[],selected:null,detail:null,tab:"chat",mode:"normal"};
const $=s=>document.querySelector(s);
const el=(tag,cls,text)=>{const n=document.createElement(tag);if(cls)n.className=cls;if(text!==undefined)n.textContent=text;return n};
async function api(path,options={}){const headers={"Content-Type":"application/json",...(options.headers||{})};if(options.method&&options.method!=="GET")headers["X-AIOS-CSRF"]=state.csrf;const r=await fetch(path,{...options,headers});const data=await r.json();if(!r.ok)throw new Error(data.error||`HTTP ${r.status}`);return data}
function fmtTime(v){if(!v)return "";return new Date(v.replace(" ","T")+"Z").toLocaleString([],{month:"short",day:"numeric",hour:"2-digit",minute:"2-digit"})}
function groupFor(s){if(["running","queued","retrying","budget_deferred"].includes(s))return "ACTIVE";if(["dead_letter","failed","terminal_failure","needs_review","blocked_capability","needs_authority","degraded"].includes(s))return "NEEDS ATTENTION";return "RECENT"}
async function boot(){const b=await api("/api/bootstrap");state.csrf=b.csrf_token;state.tasks=b.tasks;$("#workspace-name").textContent=b.workspace;$("#model-name").textContent=`${b.provider} · ${b.model}`;$("#runtime-state").textContent=b.runtime_state;$("#runtime-dot").className=`dot ${b.runtime_state}`;renderTasks();if(!state.selected&&state.tasks.length)selectTask(state.tasks[0].id)}
function renderTasks(){const root=$("#task-groups");root.replaceChildren();for(const group of ["ACTIVE","NEEDS ATTENTION","RECENT"]){const items=state.tasks.filter(t=>groupFor(t.status)===group);if(!items.length)continue;root.append(el("div","group-title",group));for(const t of items){const b=el("button",`task-item ${state.selected===t.id?"active":""}`);b.append(el("span",`task-dot ${t.status}`));const c=el("span","task-copy");c.append(el("strong","",t.title));c.append(el("small","",`${t.status.replaceAll("_"," ")} · ${fmtTime(t.updated_at)}`));b.append(c);b.onclick=()=>selectTask(t.id);root.append(b)}}}
async function selectTask(id){state.selected=id;renderTasks();try{state.detail=await api(`/api/tasks/${id}`);$("#empty-state").classList.add("hidden");$("#task-view").classList.remove("hidden");$("#task-id").textContent=`TASK ${id}`;$("#task-title").textContent=state.detail.task.title;const sp=$("#task-status");sp.textContent=state.detail.task.status.replaceAll("_"," ");sp.className=`status-pill ${state.detail.task.status}`;$("#retry-task").classList.toggle("hidden",!["completed","dead_letter","failed","terminal_failure","degraded","blocked_capability","needs_authority","needs_review"].includes(state.detail.task.status));renderTab();renderActivity();renderBudget()}catch(e){toast(e.message)}}
function setTab(tab){state.tab=tab;document.querySelectorAll(".tabs button").forEach(b=>b.classList.toggle("active",b.dataset.tab===tab));renderTab()}
function renderTab(){const root=$("#tab-content");root.replaceChildren();if(!state.detail)return;if(state.tab==="chat")renderChat(root);if(state.tab==="activity")renderActivityList(root,state.detail.activity);if(state.tab==="files")renderFiles(root);if(state.tab==="evidence")renderEvidence(root);if(state.tab==="evolution")renderEvolution(root)}
function renderChat(root){for(const m of state.detail.chat){const box=el("div",`message ${m.role}`);box.append(el("div","message-label",m.role.toUpperCase()));box.append(el("div","message-body",m.content));root.append(box)}if(state.detail.activity.length){const c=el("div","card");c.append(el("h3","",`${state.detail.activity.length} runtime events recorded`));c.append(el("p","","Open Activity for the execution timeline, or switch to Inspect for evidence and evolution decisions."));root.append(c)}}
function renderActivityList(root,items){if(!items.length)return root.append(el("p","muted","No trace events are bound to this task yet."));const grid=el("div","card-grid");for(const a of items){const c=el("div","card");const h=el("h3");h.append(el("span",`actor ${a.actor}`,a.actor));h.append(document.createTextNode(a.label));c.append(h);c.append(el("p","",`${a.created_at}${a.attempt?` · attempt ${a.attempt}`:""}${a.detail?`\n${a.detail}`:""}`));grid.append(c)}root.append(grid)}
async function renderFiles(root){for(const p of state.detail.artifacts||[]){const row=el("div","file-row");row.append(el("span","",p));const b=el("button","secondary","Preview");b.onclick=()=>previewFile(p);row.append(b);root.append(row)}if(!(state.detail.artifacts||[]).length)root.append(el("p","muted","No task artifacts were declared."));const all=el("button","secondary","Browse workspace");all.style.marginTop="16px";all.onclick=async()=>{try{const files=await api("/api/files");root.replaceChildren();files.filter(x=>!x.is_dir).forEach(f=>{const row=el("div","file-row");row.append(el("span","",f.path));const b=el("button","secondary","Open");b.onclick=()=>previewFile(f.path);row.append(b);root.append(row)})}catch(e){toast(e.message)}};root.append(all)}
async function previewFile(path){try{const f=await api(`/api/file?path=${encodeURIComponent(path)}`);openDrawer(f.path);$("#drawer-content").replaceChildren(el("pre","",f.content))}catch(e){toast(e.message)}}
function renderEvidence(root){const grid=el("div","card-grid");for(const [k,v] of Object.entries(state.detail.evidence)){const c=el("div","card");c.append(el("h3","",k.replaceAll("_"," ")));c.append(el("pre","",typeof v==="string"?v:JSON.stringify(v,null,2)));grid.append(c)}root.append(grid)}
function renderEvolution(root){const runs=state.detail.evolution||[];if(!runs.length)return root.append(el("p","muted","No evolution run is bound to this task."));for(const run of runs){const row=el("div","evolution-row");const c=el("div");c.append(el("strong","",`${run.trigger} · ${run.status}`));c.append(el("p","muted",`Model: ${run.model_intended_decision||"—"} · Host: ${run.effective_host_decision||"—"}`));row.append(c);row.append(el("span","actor HOST",run.candidate_id?"CANDIDATE":"OBSERVED"));row.onclick=()=>run.candidate_id?showCandidate(run.candidate_id):showRun(run);root.append(row)}}
function renderActivity(){const root=$("#activity-stream");root.replaceChildren();const items=(state.detail?.activity||[]).slice(-30);$("#event-count").textContent=items.length;if(!items.length)return root.append(el("p","muted","No activity yet. The Runtime may be waiting in another terminal."));for(const a of items){const row=el("div","activity-item");const line=el("div","activity-line");line.append(el("div","activity-node",a.actor[0]));row.append(line);const copy=el("div","activity-copy");copy.append(el("strong","",a.label));copy.append(el("small","",`${a.actor} · ${fmtTime(a.created_at)}`));if(a.detail)copy.append(el("p","",a.detail));row.append(copy);root.append(row)}root.scrollTop=root.scrollHeight}
function renderBudget(){const root=$("#budget-card");if(!state.detail)return root.classList.add("hidden");root.classList.remove("hidden");root.replaceChildren(el("div","eyebrow","TASK BUDGET"));for(const [label,used,max] of [["Tokens",state.detail.budget.tokens,state.detail.budget.token_limit],["Model calls",state.detail.budget.model_calls,state.detail.budget.model_call_limit],["Tool calls",state.detail.budget.tool_calls,state.detail.budget.tool_call_limit],["Cycles",state.detail.budget.cycles,state.detail.budget.cycle_limit]]){const row=el("div","budget-row");const l=el("div","budget-label");l.append(el("span","",label));l.append(el("span","",`${Number(used).toLocaleString()} / ${Number(max).toLocaleString()}`));row.append(l);const bar=el("div","bar");const fill=el("span");fill.style.width=`${Math.min(100,(Number(used)||0)/(Number(max)||1)*100)}%`;bar.append(fill);row.append(bar);root.append(row)}}
function showRun(run){openDrawer(`${run.trigger} · ${run.status}`);$("#drawer-content").replaceChildren(el("pre","",JSON.stringify(run,null,2)))}
async function showCandidate(id){try{const d=await api(`/api/candidates/${id}`);openDrawer(id);const root=$("#drawer-content");root.replaceChildren();const meta=el("div","card");meta.append(el("h3","",`${d.status} · source task ${d.source_task_id}`));meta.append(el("p","",`Changed: ${(d.changed_paths||[]).join(", ")||"none"}`));root.append(meta);for(const diff of d.diffs){root.append(el("h3","",diff.path));const box=el("div","diff");diff.old.forEach(x=>box.append(el("div","diff-line del",`- ${x}`)));diff.new.forEach(x=>box.append(el("div","diff-line add",`+ ${x}`)));root.append(box)}const details=el("div","card");details.style.marginTop="14px";details.append(el("h3","","Host evaluation"));details.append(el("pre","",JSON.stringify(d.evaluation||{status:"not evaluated"},null,2)));root.append(details)}catch(e){toast(e.message)}}
function openDrawer(title){$("#drawer-title").textContent=title;$("#drawer").classList.remove("hidden");$("#drawer-backdrop").classList.remove("hidden")}
function closeDrawer(){$("#drawer").classList.add("hidden");$("#drawer-backdrop").classList.add("hidden")}
function toast(msg){const t=$("#toast");t.textContent=msg;t.classList.remove("hidden");setTimeout(()=>t.classList.add("hidden"),3000)}
document.querySelectorAll(".tabs button").forEach(b=>b.onclick=()=>setTab(b.dataset.tab));document.querySelectorAll(".mode-switch button").forEach(b=>b.onclick=()=>{state.mode=b.dataset.mode;document.body.classList.toggle("inspect-mode",state.mode==="inspect");document.querySelectorAll(".mode-switch button").forEach(x=>x.classList.toggle("active",x===b));if(state.mode==="normal"&&["evidence","evolution"].includes(state.tab))setTab("chat")});
$("#composer").onsubmit=async e=>{e.preventDefault();const request=$("#prompt").value.trim();if(!request)return;try{const r=await api("/api/tasks",{method:"POST",body:JSON.stringify({request})});$("#prompt").value="";await boot();await selectTask(r.task_id);toast(`Task ${r.task_id} queued`)}catch(e){toast(e.message)}};$("#prompt").onkeydown=e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();$("#composer").requestSubmit()}};$("#new-task").onclick=()=>$("#prompt").focus();$("#retry-task").onclick=async()=>{try{await api(`/api/tasks/${state.selected}/retry`,{method:"POST",body:"{}"});await boot();await selectTask(state.selected);toast("Task queued for retry")}catch(e){toast(e.message)}};$("#close-drawer").onclick=closeDrawer;$("#drawer-backdrop").onclick=closeDrawer;
boot().catch(e=>toast(e.message));setInterval(async()=>{try{const selected=state.selected;await boot();if(selected)await selectTask(selected)}catch(_){}},5000);
const taskTabs=document.querySelector(".tabs");taskTabs.addEventListener("wheel",e=>{if(taskTabs.scrollWidth<=taskTabs.clientWidth||Math.abs(e.deltaX)>=Math.abs(e.deltaY))return;e.preventDefault();taskTabs.scrollLeft+=e.deltaY},{passive:false});
taskTabs.addEventListener("click",e=>{const button=e.target.closest("button");if(button)button.scrollIntoView({behavior:"smooth",block:"nearest",inline:"center"})});
